### ISSUE TITLE
URL Excludelist

### ISSUE THREAD

**Issue by stackpivot** [343max/TabHibernation#10] opened 2013-03-16 15:57 UTC
add a configurable list of pages, that are not send to sleep when sleep-button is pushed.
This would be interesting for sites with dynamic Contant (Chats, Socialnetworks.)

**Comment by moritzadler** [comment] 2013-03-18 09:58
Propose to merge with this issue (whitelist URLs from sending to sleep): https://github.com/343max/TabHibernation/issues/2

**Comment by HorayNarea** [comment] 2016-02-19 09:16
@moritzadler is right
duplicate of #2

**Closed as completed by HorayNarea** 2016-02-19 09:16 UTC
